language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
    global:
        - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
    matrix:
        - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_ATLAS="true" NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17.0" COVERAGE="true" INSTALL_GLPK="true"
        - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_ATLAS="true" NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17.0"COVERAGE="true" INSTALL_GLPK="false"
sudo: required
before_install:
  - "wget https://snap.stanford.edu/snappy/release/snap-1.2-2.4-centos6.5-x64-py2.6.tar.gz"
  - "tar zxf snap-1.2-2.4-centos6.5-x64-py2.6.tar.gz"
  - "cd snap-1.2-2.4-centos6.5-x64-py2.6/"
  - "sudo python setup.py install"
  - "cd .."
  - "sudo pip install cvxpy"

# command to install dependencies
install: "sudo python setup.py install"
# command to run tests
script:  bash Tests/test_script.sh
